export const SET_CONTACTS= "SET_CONTACTS";
export const RESET_CONTACTS= "RESET_CONTACTS";
export const SET_SPECIFIC_CONTACTS= "SET_SPECIFIC_CONTACTS";
export const RESET_SPECIFIC_CONTACTS= "RESET_SPECIFIC_CONTACTS";
