export const SET_DEALS = "SET_DEALS";
export const RESET_DEALS = "RESET_DEALS";
export const SET_SPECIFIC_DEAL = "SET_SPECIFIC_DEAL";
export const RESET_SPECIFIC_DEAL = "RESET_SPECIFIC_DEAL";
// export const SET_SUB_CATEGORIES = "SET_SUB_CATEGORIES";
// export const RESET_SUB_CATEGORIES = "RESET_SUB_CATEGORIES";
// export const SET_SPECIFIC_SUB_CATEGORIES = "SET_SPECIFIC_SUB_CATEGORIES";
// export const RESET_SPECIFIC_SUB_CATEGORIES = "RESET_SPECIFIC_SUB_CATEGORIES";
